---
- hosts: localhost
  become: yes
  tasks:
    - local_action:
        aws_access_key: AKIAZ5PLBQBRQMMBJM5R
        aws_secret_key: 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
        module: ec2
        instance_tags:
          Name: 
            - Prod-Instance
            - Admin-Instance
        state: absent
        region: us-west-2