---
- hosts: localhost
  become: yes
  tasks:
    - ec2:
        aws_access_key: AKIAZ5PLBQBRQMMBJM5R
        aws_secret_key: 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
        instance_ids: i-0b727cc137d817daf
        region: us-west-2
        state: stopped
        vpc_subnet_id: subnet-0f4ef045
        assign_public_ip: yes