---
- hosts: localhost
  become: yes
  tasks:
    - ec2_vol:
        aws_access_key: AKIAZ5PLBQBRQMMBJM5R
        aws_secret_key: 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
        volume_size: 10
        device_name: /dev/sdb1
        volume_type: io1
        iops: 100
        zone: us-west-2a
        region: us-west-2
        tags:
          Name: Test-Volume