---
- hosts: localhost
  become: yes
  tasks:
    - ec2_vol:
        aws_access_key: AKIAZ5PLBQBRQMMBJM5R
        aws_secret_key: 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
        id: vol-02f3ca8625b0eb917
        state: absent
        zone: us-west-2b
        region: us-west-2

