---
- name: This is my first playbook yaml file
  hosts: all
  become: yes
  tasks:
    - name: This is to copy the /etc/passwd to /tmp
      copy:
        src: /etc/passwd
        dest: /tmp
        owner: ravi
        group: ravi
        mode: 0777

    - name: This is to create aws directory
      file:
        path: /tmp/aws
        state: directory

    - name: This task is used to install tree package
      apt:
        name: tree
        update_cache: yes
        state: present

