---
- name: installing java on centos 7.8
  hosts: centos
  become: yes
  tasks:
    - name: Installing java-11-openjdk
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_facts['os_family'] == "RedHat"