---
- name: installing java on ubuntu 18.04
  hosts: all
  become: yes
  tasks:
    - name: installing openjdk-8-jdk
      apt:
        name: "{{ java_package }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Installing java-11-openjdk
      yum:
        name: "{{ java_package }}"
        state: present
      when: ansible_facts['os_family'] == "RedHat"      