---
- name: installing java on ubuntu 18.04
  hosts: all
  become: yes
  tasks:
    - name: installing openjdk-8-jdk
      apt:
        name: openjdk-8-jdk
        state: present
      when: ansible_facts['os_family'] == "Debian"