---
- name: This is to demonstrate notify and handlers
  hosts: all
  tasks:
    - lineinfile:
        path: /etc/ssh/sshd_config
        line: DenyUsers naresh
      notify: myhandler1

    - copy:
        src: /etc/passwd
        dest: /tmp

  handlers:
    - name: myhandler1
      service:
        name: sshd
        state: restarted