---
- name: "This is single line format playbook"
  hosts: all
  become: yes
  tasks:
    - copy: src=/etc/shadow dest=/tmp/ owner=ravi mode=0666
    - file: path=/tmp/azure state=directory
    - apt: name=nfs-kernel-server state=present