---
        - name: This task is used to install tree package
          apt:
            name: apache2
            update_cache: yes
            state: present

        - name: This task is used to run the apache2 service
          service:
            name: apache2
            state: started
            enabled: yes