---
- hosts: all
  become: yes
  vars:
    myfile:
      - /etc/passwd
      - /etc/group
      - /etc/fstab
    mydir:
      - /tmp
      - /mnt
      - /opt
  tasks:
    - copy:
        src: "{{ item[0] }}"
        dest: "{{ item[1] }}"
      with_nested:
        - "{{ myfile }}"
        - "{{ mydir }}"
  