---
- hosts: all
  become: yes
  vars:
    mydir:
      - /tmp
    myfile:
      - /etc/passwd
  tasks:
    - copy:
        src: "{{ item }}"
        dest: "{{ item }}"
      with_items:
        - "{{ myfile }}"
        - "{{ mydir }}"
        