---
- hosts: all
  tasks:
    - copy:
        src: /etc/passwd
        dest: /tmp
        owner: wipro
        group: tcs
        mode: 777
    
    - file:
        path: /tmp/ansible
        state: directory

    - apt:
        name: wget
        state: present
